name: my-container-app
metadata:
  template: azd-init@1.9.4
workflows:
  up: 
    steps:
      - azd: provision
      - azd: deploy --all
services:
  api:
    image: mono:latest
    host: function
    settings:
        CONTAINER_REGISTRY_USERNAME: mahi402
        CONTAINER_REGISTRY_PASSWORD: ${{vars.REGISTRY_PASSWORD}}
    bindings: 
        - type: httpTrigger 
          authLevel: function
    linuxFxVersion: "DOCKER|mahi402.azurecr.io/mono:latest"
  web:
    project: ./src/web
    dist: dist
    language: js
    host: staticwebapp
 