name: my-container-app
metadata:
  template: azd-init@1.9.4
workflows:
  up: 
    steps:
      - azd: provision
      - azd: deploy --all
services:
  api:
    image: mahi402.azurecr.io/mono:latest
    host: function
  web:
    project: ./src/web
    dist: dist
    language: js
    host: staticwebapp
 